lavv17/lftp

src/MirrorJob.cc

Running chmod will clear sgid permissions on directories when current user
is not a member of directory group even when actually nothing is explicitly
changed.

mirror: don't set u+rwx on directories if already set

---

src/SFtp.cc

This fixes a problem with sftp causing "file size decreased during transfer" errors, which was seen with lftp versions before 4.5.0. The problem wasn't reproduced in 4.5.0 and later versions, but it seems this might be just a side effect of the changes in SMTask which were included in 4.5.0, and this situation could theoretically still happen, if not with the current code, maybe later with future changes.

sftp: flush file buffer in DONE state before returning EOF

---

src/Resolver.cc

The `IN6_IS_ADDR_LINKLOCAL` is specified to take a `const struct in6_addr*`, and to be portable across platforms a cast seems to be needed. Fixes #306.

Resolver.cc: Cast address to IN6_IS_ADDR_LINKLOCAL

---

src/Makefile.am

On OS X Yosemite and below, the system OpenSSL headers are in
/usr/include, which also happens to have zlib.h, so in order to use a
non-system version of OpenSSL together with the system version of zlib,
the OPENSSL_CPPFLAGS need to precede the ZLIB_CPPFLAGS in the order of
includes.
Fixes #317.

include openssl before zlib

---

configure.ac
m4/ax_check_zlib.m4
m4/ax_lib_expat.m4
m4/lftp_lib_readline.m4

-R option is needed for executable to find the library in a non-standard place.
Also fixed zlib check (save flags properly; avoid duplicating the flags).
May fix #336 (please check)

m4: add -R option for runtime path to libraries

---

src/ftpclass.cc

RFC 3659 says that the server is not required to accept the 'OPTS MLST'
command before authentication. So send it after login.

ftp: Send 'OPTS MLST' after login

---

m4/lftp_lib_readline.m4

Hi,
There is a missing '-f' in test args, leading to the test being true even if the file does not exist. Find attached a patch to fix that problem.
Best regards,
Ganael.

Add missing -f in readline test

---

doc/lftp.1

Avoid information loss in both groff and mandoc (".PP text" to ".PP\ntext").

avoid information loss in both groff and mandoc

---

src/EditJob.cc
src/commands.cc

Fish does not allow variable expansion `${EDITOR:-vi}`:
> fish: Variables may not be used as commands. In fish, please define a function or use 'eval $EDITOR:-vi'.
> ${EDITOR:-vi} /home/simon/.lftp/edit/simon-314159.README

fix(edit): add compatibility with fish

---

src/Torrent.cc
src/commands.cc
src/ftpclass.cc

Hi,
I'm a PhD student. I analyzed the lftp source code and found some potential API bugs that may cause crashes.
These crashes are mainly caused by insufficient error handling of API functions like listen or truncate.
I think it's unsafe to assume the library function would be correct. It would be better if we could handle the error properly (at least print error message).
Best,
Zhouyang

Fix crashes when some external APIs fail

---

doc/lftp.1

The `du` and `history` commands do not appear to be documented in the `lftp(1)` manual page.  This PR documents the commands in `lftp.1`, based on the command help text.
Thanks for considering,
Kevin

lftp.1: Document du and history commands

---

src/ftpclass.cc
src/ftpclass.h

This adds support for CEPR (#475), which also allows better handling of EPSV using a proxy (see #466).

Added support for CEPR (Custom Extended Passive Reply)

---

.travis.yml

Container environments are obsolete. See
- https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
- https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
for the reasons given by Travis-CI.

travis.yml: don't try to run our builds in a container

---

src/Torrent.cc

It's possible that with DHT enabled, lftp will try to bind and
listen on a port, chosen from torrent:port-range and if other
lftp instances are running and ports from that range are already
in use, starting another lftp instance will SIGSEGV, as the sock
will be set to -1. See GitHub lftp issue #511 for more details.
To reproduce the issue, start lftp via:
lftp -c 'torrent --dht-bootstrap=dht.example.com sample.torrent'
as many times as it's needed to exhaust torrent:port-range. Before
this change, lftp would segfault in PollVec::AddFD() with fd=-1.

In MaySendUDP() handle case when socket may not be available yet

---

doc/lftp.1
src/resource.cc

Hi
I adjusted the defaults for more security.
The speed concerns are mitigated on most systems today, the argument is on this website: https://istlsfastyet.com/
If you would like me to change anything at this PR, please tell me.
Cheers,
Stefan

Enable TLS by default

---

src/FileCopy.cc
src/NetAccess.cc
src/ResMgr.cc
src/Speedometer.cc
src/TimeDate.cc
src/ftpclass.cc
src/misc.cc
trio/trio.c
trio/trionan.c
trio/triostr.c

- Replace "math.h" includes with "cmath".
This should fix https://github.com/lavv17/lftp/issues/273.
- Delete includes of "strftime.h". This is because this file only includes the function _nstrftime_, which is not used anywhere.
This should fix https://github.com/lavv17/lftp/issues/535.
Note that this PR doesn't fix all known compilation issues (specifically, https://github.com/lavv17/lftp/issues/376 remains, and it will probably fail the Travis CI build for this PR).

Fix some compilation issues

---

doc/lftp.1
src/resource.cc

Currently, LFTP sends an ALLO command before each STOR, to ask the server to allocate storage space for the subsequent transfer.
But, the ALLO command is useless on any modern (or slightly modern) FTP server, and in many cases it is implemented as a no-operation.
As mentioned in one of the comments in the LFTP source code: "ALLO is usually ignored by servers, but send it anyway."
The result is that a redundant command is sent for each store command, and I can only think of disadvantages stemming from this fact.
Thus, I changed the default setting to not sending ALLO commands.

Stop sending ALLO commands by default

---

src/ftpclass.cc

Otherwise this fails with:
```
ftpclass.cc: In member function ‘Ftp::pasv_state_t Ftp::Handle_EPSV_CEPR()’:
ftpclass.cc:854:53: error: ‘union sockaddr_u’ has no member named ‘in6’; did you mean ‘in’?
854 |       inet_pton(AF_INET6, pasv_addr, &conn->data_sa.in6.sin6_addr);
|                                                     ^~~
|                                                     in
ftpclass.cc:855:21: error: ‘union sockaddr_u’ has no member named ‘in6’; did you mean ‘in’?
855 |       conn->data_sa.in6.sin6_port=htons(port);
|                     ^~~
|                     in
```

Fix build with --disable-ipv6

---

m4/lftp_lib_readline.m4

When readline is static library, we need to link against ncurses
because readline needs ncurses. It is because, dependent library's
symbols are not resolved when static library is built. Those symbols
are resolved program tries to link with static library.
We can't pass linker flags for ncurses by setting LIBS environment
variable via <PKG>_CONF_ENV because it looks like build system is not
taking that into account and even though it would have been, order of
linking is important.
We can't also pass linker flags for ncurses via --with-readline-libs
conf options because it causes lftp_LIB_READLINE macro to take readline
headers from host machine if available. To use --with-readline-libs
we need to set --with-readline=yes and --with-readline-inc to include
dir. But when --with-readline=yes, …

m4/lftp_lib_readline.m4: fix static link with readline

---

src/lftp_ssl.cc

Hello,
This patch fixes the following build errors with LibreSSL (3.1.4) :
```
/bin/sh ../libtool --silent  --tag=CXX   --mode=compile c++ -DHAVE_CONFIG_H -I. -I../lib  -I../lib -I../trio  -I/usr/include  -DLIBICONV_PLUG -I/usr/local/include -isystem /usr/local/include -D_THREAD_SAFE  -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include  -Wall -Wwrite-strings -Woverloaded-virtual -fno-exceptions -fno-rtti -fno-implement-inlines -MT liblftp_network_la-lftp_ssl.lo -MD -MP -MF .deps/liblftp_network_la-lftp_ssl.Tpo -c -o liblftp_network_la-lftp_ssl.lo `test -f 'lftp_ssl.cc' || echo './'`lftp_ssl.cc
lftp_ssl.cc:1164:10: error: use of undeclared identifier 'X509_STORE_CTX_get_by_subject'; did you mean …
```

Fix build with LibreSSL (following commit 537f37898)

---

configure.ac

See: https://github.com/coreutils/gnulib/blob/master/NEWS#L6
Otherwise the building process show errors:
```
./bootstrap: Bootstrapping from checked-out lftp sources...
./bootstrap: consider installing git-merge-changelog from gnulib
./bootstrap: getting gnulib files...
Cloning into 'gnulib'...
remote: Counting objects: 10343, done.
remote: Compressing objects: 100% (9028/9028), done.
remote: Total 10343 (delta 5355), reused 2904 (delta 1293)
Receiving objects: 100% (10343/10343), 8.83 MiB | 242.00 KiB/s, done.
Resolving deltas: 100% (5355/5355), done.
Updating files: 100% (10273/10273), done.
./bootstrap: autopoint --force
Copying file ABOUT-NLS
Copying file build-aux/config.rpath
Copying file m4/codeset.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4 …
```

Bump autoconf minimum version to 2.64

---

configure.ac
po/sr.po

This PR adds `po/sr.po` and updates the list of languages in `configure.ac` to include `sr`.

Add Serbian translation

---

src/lftp_ssl.cc

`X509_OBJECT_get0_X509_CRL` is provided by libressl since version 2.7.0 and https://github.com/libressl-portable/openbsd/commit/9866ae34c0af718973475296bd9ef036d3aaa94e resulting in the following build failure:
```
/nvmedata/autobuild/instance-21/output-1/host/opt/ext-toolchain/bin/../lib/gcc/microblaze-buildroot-linux-musl/11.2.0/../../../../microblaze-buildroot-linux-musl/bin/ld: /nvmedata/autobuild/instance-21/output-1/host/microblaze-buildroot-linux-musl/sysroot/usr/lib/libcrypto.a(x509_lu.c.o): in function `X509_OBJECT_get0_X509_CRL':
(.text+0xc3c): multiple definition of `X509_OBJECT_get0_X509_CRL'; /nvmedata/autobuild/instance-21/output-1/build/lftp-4.9.2/src/.libs/liblftp-network.a(liblftp_network_la-lftp_ssl.o):(.text+0x894): first defined here
```
Fixes:
- …

src/lftp_ssl.c: fix build with libressl >= 2.7.0

---

tests/http-get.cc

the former lftp homepage lftp.tech is now a parked domain: https://lftp.tech
Changing the test back to the project homepage.

the domain lftp.tech is dead -> switching back to former homepage lftp.yar.ru

---

src/PollVec.h

IN and OUT are used by PollVec mask functions to determine which fd_sets
to use in AddFD, FDReady, and FDSetNotReady, however these enums are not
used outside of PollVec code and the rest of the code uses POLLIN and
POLLOUT definitions instead. This works on many POSIX platforms since
the enum values match the POLLIN and POLLOUT values, but not on AIX
where POLLOUT is 2 instead of 4. This prevents code from determining
when a file descriptor is writeable, leading to a hang when using FTPS
protocol (at least).
Fixes #672

Ensure that PollVec enum matches poll values

---

src/GetFileInfo.cc

fix issue #674
fix #674 : lftp still crashes with segmentation violation when running "find",after the patch: fill verify_fn in case of cd error;

fill verify_fn for quickly second segmentation violation

---

src/lftp_ssl.cc

* `X509_STORE_CTX_get_by_subject` was added in LibreSSL `3.5.0`
* `SSLeay_add_ssl_algorithms()` and `SSL_load_error_strings()` were deprecated in LibreSSL `3.0.0`.
Fixes: https://github.com/lavv17/lftp/commit/0276d5c239c41b3a63f738a5dc47fd56ac389cf0

lftp_ssl: update LibreSSL conditionals

---

doc/lftp.1

with examples for both GnuTLS and OpenSSL
rationale: inexperimented user of lftp I naively pasted the example from manual in the lftp config file and it did not work
(as the syntax for GnuTLS differs)

more precise documentation for ssl:priority

---

src/commands.cc

Output for lftp --version
```
Libraries used: OpenSSL 3.0.8, Readline 8.2, zlib 1.2.13

update version lib display code for OpenSSL 3

---

configure.ac

After running autoreconf and configure on Ubuntu 24.04 (noble), the generated `po/Makefile` will fail to run `make install`:
```
$ make install DESTDIR=debian/lftp
[...]
Making install in po
make[4]: Entering directory 'po'
debian/lftp/usr/share
make[4]: debian/lftp/usr/share: Permission denied
```
This failure is caused by `mkdir_p` pointing to `MKDIR_P` but `MKDIR_P` not being defined in `po/Makefile`.
Upgrade to gettext version to 0.21. Then `po/Makefile` will be correct:
```
MKDIR_P = /usr/bin/mkdir -p
mkdir_p = $(MKDIR_P)
```

configure.ac: Bump gettext version to 0.21

---

src/SFtp.cc
src/SFtp.h

lftp supports making many SFTP DATA requests in parallel when downloading a file. Responses with data payloads from an sftp server can sometimes arrive in a different order from the original requests.
The out of order data payload (packets) are added to the `ooo_chain` to be processed when the expected (but late) next requested packet arrives.
A single packet being delayed while many parallel requests continue to be made can sometimes result in the `Too many out-of-order packets` message if the `ooo_chain` buffer of 64 entries is exceeded.
This fix checks the remaining capacity of the `ooo_chain` and pending requests (`RespQueueSize()`) and will avoid sending new requests for more data until the `ooo_chain` is processed or `RespQueueSize()` shrinks. Adding this constraint does mean that …

Attempt to fix SFTP issue #636 Too many out-of-order packets.

---

doc/lftp.1
src/SFtp.cc
src/SFtp.h

I've come across SFTP servers that (as a questionable decision):
1. Don't support `FSETSTAT`; and
2. Consider any failed operation during a transfer a failure of the transfer - keeping the transferred file in a staging directory (to be later cleaned up) instead of moving it to its final destination.
This PR adds a configuration parameter for SFTP to skip sending `FSETSTAT` after the file is written.

Add option for skipping FSETSTAT

---

src/ResMgr.h

I tried this based on the example and also got a core. If the syntax is incorrect or has missing parts, , there should be an error message. A simple fix that does a NULL check is attached.
lftpget sftp://jai@127.0.0.1:22:/home/jai/.bash_profile .
Core was generated by `lftp -c set cmd:at-exit;set xfer:max-redirections 16;  get1  "sftp://jai@127.0.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000565bda146512 in ResMgr::str2bool (s=0x0) at ResMgr.cc:587
587        return(strchr("TtYy1+",s[0])!=0 || !strcasecmp(s,"on"));
(gdb) bt
#0  0x0000565bda146512 in ResMgr::str2bool (s=0x0) at ResMgr.cc:587
#1  0x0000565bda143aed in ResValue::to_bool (this=0x7ffc4705d880) at /home/jai/Work/lftp/src/ResMgr.h:164
#2  0x0000565bda147d6a in ResClient::QueryBool (this=0x565be0b02ce8, …

#735: fix for SEGV with lftpget
